ekf_se_map:
  frequency: 30
  sensor_timeout: 0.1
  two_d_mode: true
  map_frame: map  
  odom_frame: odom
  base_link_frame: base_link
  world_frame: map

  odom0: "/poseupdate"
  odom0_config: [true,  true,  false,
                 false, false, true,
                 false, false, false,
                 false, false, true,
                 false, false, false]
  odom0_queue_size: 10
  odom0_nodelay: false
  odom0_differential: false
  odom0_relative: false

  imu0: "/imu/data"
  imu0_config: [false, false, false,
                true,  true,  true,
                false, false, false,
                false, false, true,
                true,  true,  false]
  imu0_nodelay: false
  imu0_differential: false
  imu0_relative: false
  imu0_queue_size: 10
  use_map_frame: true
