global_frame: map
robot_base_frame: base_link
odom_frame: odom
obstacle_range: 3.0
raytrace_range: 3.0
footprint: [[-0.16, -0.08], 
            [-0.16, 0.08], 
            [0.16, 0.08], 
            [0.16, -0.08]]
inflation_radius: 0.4
transform_tolerance: 3


observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: laser_scan, marking: true, clearing: true}
